name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.12', '3.13']
        django: ['4.2', '5.2']
        exclude:
          - python: '3.13'
            django: '4.2'

    name: Run the test suite (Python ${% templatetag openvariable %} matrix.python {% templatetag closevariable %}, Django ${% templatetag openvariable %} matrix.django {% templatetag closevariable %})

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${% templatetag openvariable %} matrix.python {% templatetag closevariable %}

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - name: Run tests
        run: tox
        env:
          PYTHON_VERSION: ${% templatetag openvariable %} matrix.python {% templatetag closevariable %}
          DJANGO: ${% templatetag openvariable %} matrix.django {% templatetag closevariable %}

      - name: Publish coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${% templatetag openvariable %} secrets.CODECOV_TOKEN {% templatetag closevariable %}

  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    needs: tests
    environment: release
    permissions:
      id-token: write

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build sdist and wheel
        run: |
          pip install build --upgrade
          python -m build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

