language: python
cache: pip

sudo: false

python:
  - "3.6"

env:
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: DJANGO=1.11 }
    - { python: "3.6", env: DJANGO=2.0 }
    - { python: "3.6", env: TOXENV=isort }

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
